### ISSUE TITLE
Thor folder not included

### ISSUE THREAD

**Issue by Rimmuru** [pushbuttonreceivecode/SFML-GUI-Button#1]
In your button.hpp you have 2 includes from a folder called thor. But the folder is not present on the repo.
`
#include <THOR/Graphics.hpp>
#include <THOR/Shapes.hpp>
`

**Comment by pushbuttonreceivecode** [comment]
Wow...talk about a sleeper of a ticket. First of all, I must apologize for the lack of details in the repo README file. Many moons ago, I wrote SFML tutorials while I was learning some C++ and graphics programming. The tutorials I wrote were moved from the original blog (pushbuttonreceivecode.com) and archived to a more long term home. You can find the write up for this repo here:
[Simple Buttons with SFML](https://code.markrichards.ninja/sfml/how-to-create-simple-buttons-for-your-sfml-game)
I omitted some details regarding the dependencies for this repo. As it stands, the button example depends on the [Thor](https://github.com/Bromeon/Thor) library for SFML which, at the time, featured many utilities for drawing shapes amongst other features that were beyond the scope of what SFML offered. While I can't guarantee that the Thor and/or SFML APIs haven't changed, I think if you can build and include Thor there's a good chance it will work out of the box. I have no plans to support any of these repositories but I do hope that they are helpful to some as long as SFML exists and the API remains similar.

I really appreciate you raising the issue instead of just moving on and forgetting about it. Let me know if you find any other issues like this or others and I'll do my best to clarify and hopefully make some minor updates where possible.

**Comment by Rimmuru** [comment]
yeah i know right lol 
Randomly stumbled upon this while looking for better/not over engineered ways of doing buttons.
They are a huge help with what im doing, really. 

Thanks alot for actually responding even after the repo is 7 years old, I'll keep you in the loop of any other issues.
Besides updating the colour from the depreciated `sf::setColor` to the non depreciated `sf::setFillColor` and the (was) missing lib it works great.

**Comment by pushbuttonreceivecode** [comment]
I'm going to go ahead and close this issue, I [updated the README](https://github.com/pushbuttonreceivecode/SFML-GUI-Button/commit/42bb0cb92a2862055ce55cbf0e7d36e97aba5a35) to indicate the Thor dependency. Thanks again.
